#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# //////////////////////////////////////////////////////////////////////////////////////////////// #

hackthon.palestrante.palestrante:
    resource: '@ApplicationHackthonPalestranteBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.diaevento.diaevento:
    resource: '@ApplicationHackthonDiaEventoBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.atividadeevento.atividadeevento:
    resource: '@ApplicationHackthonAtividadeEventoBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.local.local:
    resource: '@ApplicationHackthonLocalBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.galeria.galeria:
    resource: '@ApplicationHackthonGaleriaBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.patrocinador.patrocinador:
    resource: '@ApplicationHackthonPatrocinadorBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.faq.faq:
    resource: '@ApplicationHackthonFaqBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.faleconosco.faleconosco:
    resource: '@ApplicationHackthonFaleConoscoBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.banner.banner:
    resource: '@ApplicationHackthonBannerBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.sobre.sobre:
    resource: '@ApplicationHackthonSobreBundle/Resources/config/routes/routes.yaml'
    prefix: /

hackthon.evento.evento:
    resource: '@ApplicationHackthonEventoBundle/Resources/config/routes/routes.yaml'
    prefix: /

